/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.jparking.gui;

//import static javafx.application.Platform.exit;

import edu.ucue.jparking.dao.excepciones.CampusNoExistenteException;
import edu.ucue.jparking.dao.excepciones.ParqueaderoNoExistenteException;
import edu.ucue.jparking.dao.excepciones.UsuarioNoExistenteException;
import edu.ucue.jparking.srv.CampusService;
import edu.ucue.jparking.srv.ParqueaderoService;
import edu.ucue.jparking.srv.UsuarioService;
import edu.ucue.jparking.srv.enums.TipoUsuario;
import edu.ucue.jparking.srv.excepciones.CedulaNoValidaException;
import edu.ucue.jparking.srv.excepciones.CodigoNoValidoException;
import edu.ucue.jparking.srv.objetos.Campus;
import edu.ucue.jparking.srv.objetos.Parqueadero;
import edu.ucue.jparking.srv.objetos.Usuario;
import java.util.Set;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Franklin Lara
 * @author Santos Gallegos
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
        
        
        
        //Establecer icono de aplicacion
        ImageIcon imgIcon = new ImageIcon("../JParking/img/transport122.png");
        this.setIconImage(imgIcon.getImage());
        
        //Listar usuarios en tabla
        listarUsuarios();
        try {
            listarParqueaderos();
        } catch (CampusNoExistenteException ex) {
        }
        
        //Cargar campus en combobox
        cargarParqueaderosCB();
        
        //Centrar ventana
        setLocationRelativeTo(null);
    }
    
    public void cargarParqueaderosCB(){
        //Cargar parqueaderos en combo box
        CampusCB.removeAllItems();
        CampusService campusService = new CampusService();
        for(Campus c : campusService.getCampus()){
            CampusCB.addItem(c.getNombre());
        }
    }
    
    public void listarUsuarios(){        
        UsuarioService usuarioService = new UsuarioService();
        
        String tipoUsuario = (String) TipoUsuarioCB.getSelectedItem();
        Set<Usuario> usuarios = null;
        switch(tipoUsuario){
            case "Todos": {
                usuarios = usuarioService.getLista();
                break;
            }
            case "Estudiante":{
                usuarios = usuarioService.getLista(TipoUsuario.ESTUDIANTE);
                break;
            }
            case "Docente": {
                usuarios = usuarioService.getLista(TipoUsuario.DOCENTE);
                break;
            }
            case "Empleado": {
                usuarios = usuarioService.getLista(TipoUsuario.EMPLEADO);
                break;
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) TablaUsuarios.getModel();
        
        //Borrar elementos anteriores
        for(int i = model.getRowCount() - 1; i >= 0 ; i--)
            model.removeRow(i);
        
        int n = 1;
        for(Usuario u : usuarios)
            model.addRow(new Object[]{n++, u.getCedula(), u.getNombres() + " " + u.getApellidos()});
    }
    
    public void listarParqueaderos() throws CampusNoExistenteException{
        ParqueaderoService parqueaderoService = new ParqueaderoService();

        String nombreCampus = (String) CampusCB.getSelectedItem();
        
        if(nombreCampus == null || nombreCampus.trim().length() == 0)
            return;
        
        Set<Parqueadero> parqueaderos = parqueaderoService.getParqueaderos(nombreCampus);

        DefaultTableModel model = (DefaultTableModel) TablaParqueaderos.getModel();

        //Borrar elementos anteriores
        for(int i = model.getRowCount() - 1; i >= 0 ; i--)
            model.removeRow(i);

        int n = 1;
        for(Parqueadero p : parqueaderos)
            model.addRow(new Object[]{n++, p.getId(), p.getUbicacion(), p.getNumeroLugares(), p.getNumeroLugaresOcupados()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampusCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaParqueaderos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        CrearParqueaderoBtn = new javax.swing.JButton();
        ModificarParqueaderoBtn = new javax.swing.JButton();
        EliminarParqueaderoBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TipoUsuarioCB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ModificarUsuarioBtn = new javax.swing.JButton();
        CrearUsuarioBtn = new javax.swing.JButton();
        EliminarUsuarioBtn = new javax.swing.JButton();
        VerBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        CampusMenu = new javax.swing.JMenu();
        CrearCampusMenuItem = new javax.swing.JMenuItem();
        ModicarCampusMenuItem = new javax.swing.JMenuItem();
        EliminarCampusMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        AdministarPuertasMenuItem = new javax.swing.JMenuItem();
        AdministarPorterosMenuItem = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        SalirItem = new javax.swing.JMenuItem();
        UsuariosMenu = new javax.swing.JMenu();
        CrearUsuarioMenuItem = new javax.swing.JMenuItem();
        ModificarUsuarioMenuItem = new javax.swing.JMenuItem();
        EliminarUsuarioMenuItem = new javax.swing.JMenuItem();
        ParqueaderosMenu = new javax.swing.JMenu();
        CrearParqueaderoMenuItem = new javax.swing.JMenuItem();
        ModificarParqueaderoMenuItem = new javax.swing.JMenuItem();
        EliminarParqueaderoMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        AgregarPuertaAccesoItem = new javax.swing.JMenuItem();
        EliminarPuertaAccesoItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        AgregarUsuarioParqueaderoItem = new javax.swing.JMenuItem();
        EliminarUsuarioParqueaderoItem = new javax.swing.JMenuItem();
        PagosMenu = new javax.swing.JMenu();
        GenerarOrdenPagoItem = new javax.swing.JMenuItem();
        RegistrosMenu = new javax.swing.JMenu();
        ListarRegistrosMenuItem = new javax.swing.JMenuItem();
        AyudaMenu = new javax.swing.JMenu();
        AcercaDeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JParking- Gestion de los Parqueaderos de la Universidad de Cuenca");

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setOneTouchExpandable(true);

        jLabel1.setText("Campus:");

        CampusCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CampusCBActionPerformed(evt);
            }
        });

        TablaParqueaderos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Id", "Ubicación", "Espacios", "Espacios ocupados"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaParqueaderos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaParqueaderos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaParqueaderos);
        if (TablaParqueaderos.getColumnModel().getColumnCount() > 0) {
            TablaParqueaderos.getColumnModel().getColumn(0).setMinWidth(30);
            TablaParqueaderos.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaParqueaderos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        CrearParqueaderoBtn.setText("Crear");
        CrearParqueaderoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearParqueaderoBtnActionPerformed(evt);
            }
        });

        ModificarParqueaderoBtn.setText("Modificar");
        ModificarParqueaderoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarParqueaderoBtnActionPerformed(evt);
            }
        });

        EliminarParqueaderoBtn.setText("Eliminar");
        EliminarParqueaderoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarParqueaderoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(CrearParqueaderoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarParqueaderoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarParqueaderoBtn)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearParqueaderoBtn)
                    .addComponent(ModificarParqueaderoBtn)
                    .addComponent(EliminarParqueaderoBtn)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Parqueaderos", jPanel2);

        jSplitPane1.setRightComponent(jTabbedPane1);

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Cedula", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsuarios.setMaximumSize(new java.awt.Dimension(2147483647, 16));
        TablaUsuarios.setMinimumSize(new java.awt.Dimension(60, 16));
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TablaUsuarios);
        if (TablaUsuarios.getColumnModel().getColumnCount() > 0) {
            TablaUsuarios.getColumnModel().getColumn(0).setMinWidth(30);
            TablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaUsuarios.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel4.setText("Tipo Usuario:");

        TipoUsuarioCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Docente", "Empleado", "Estudiante" }));
        TipoUsuarioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUsuarioCBActionPerformed(evt);
            }
        });

        ModificarUsuarioBtn.setText("Modificar");
        ModificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioBtnActionPerformed(evt);
            }
        });

        CrearUsuarioBtn.setText("Crear");
        CrearUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBtnActionPerformed(evt);
            }
        });

        EliminarUsuarioBtn.setText("Eliminar");
        EliminarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioBtnActionPerformed(evt);
            }
        });

        VerBtn.setText("Ver");
        VerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(VerBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CrearUsuarioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarUsuarioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarUsuarioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearUsuarioBtn)
                    .addComponent(ModificarUsuarioBtn)
                    .addComponent(EliminarUsuarioBtn)
                    .addComponent(VerBtn)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TipoUsuarioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 23, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TipoUsuarioCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Usuarios", jPanel1);

        jSplitPane1.setLeftComponent(jTabbedPane2);

        CampusMenu.setMnemonic('c');
        CampusMenu.setText("Campus");

        CrearCampusMenuItem.setText("Crear Campus");
        CrearCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(CrearCampusMenuItem);

        ModicarCampusMenuItem.setText("Editar Campus");
        ModicarCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModicarCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(ModicarCampusMenuItem);

        EliminarCampusMenuItem.setText("Eliminar Campus");
        EliminarCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(EliminarCampusMenuItem);
        CampusMenu.add(jSeparator1);

        AdministarPuertasMenuItem.setText("Administrar Puertas");
        AdministarPuertasMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministarPuertasMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(AdministarPuertasMenuItem);

        AdministarPorterosMenuItem.setText("Administrar Porteros");
        AdministarPorterosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdministarPorterosMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(AdministarPorterosMenuItem);
        CampusMenu.add(jSeparator6);

        SalirItem.setText("Salir");
        SalirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirItemActionPerformed(evt);
            }
        });
        CampusMenu.add(SalirItem);

        jMenuBar1.add(CampusMenu);

        UsuariosMenu.setMnemonic('u');
        UsuariosMenu.setText("Usuarios");

        CrearUsuarioMenuItem.setText("Crear Usuario");
        CrearUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(CrearUsuarioMenuItem);

        ModificarUsuarioMenuItem.setText("Modificar Usuario");
        ModificarUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(ModificarUsuarioMenuItem);

        EliminarUsuarioMenuItem.setText("Eliminar  Usuario");
        EliminarUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(EliminarUsuarioMenuItem);

        jMenuBar1.add(UsuariosMenu);

        ParqueaderosMenu.setMnemonic('p');
        ParqueaderosMenu.setText("Parqueaderos");

        CrearParqueaderoMenuItem.setText("Crear Parqueadero");
        CrearParqueaderoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearParqueaderoMenuItemActionPerformed(evt);
            }
        });
        ParqueaderosMenu.add(CrearParqueaderoMenuItem);

        ModificarParqueaderoMenuItem.setText("Modificar Parqueadero");
        ModificarParqueaderoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarParqueaderoMenuItemActionPerformed(evt);
            }
        });
        ParqueaderosMenu.add(ModificarParqueaderoMenuItem);

        EliminarParqueaderoMenuItem.setText("Eliminar Parqueadero");
        EliminarParqueaderoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarParqueaderoMenuItemActionPerformed(evt);
            }
        });
        ParqueaderosMenu.add(EliminarParqueaderoMenuItem);
        ParqueaderosMenu.add(jSeparator4);

        AgregarPuertaAccesoItem.setText("Agregar puerta de acceso");
        ParqueaderosMenu.add(AgregarPuertaAccesoItem);

        EliminarPuertaAccesoItem.setText("Eliminar puerta de acceso");
        ParqueaderosMenu.add(EliminarPuertaAccesoItem);
        ParqueaderosMenu.add(jSeparator5);

        AgregarUsuarioParqueaderoItem.setText("Agregar usuario");
        ParqueaderosMenu.add(AgregarUsuarioParqueaderoItem);

        EliminarUsuarioParqueaderoItem.setText("Eliminar usuario");
        ParqueaderosMenu.add(EliminarUsuarioParqueaderoItem);

        jMenuBar1.add(ParqueaderosMenu);

        PagosMenu.setMnemonic('g');
        PagosMenu.setText("Pagos");

        GenerarOrdenPagoItem.setText("Generar Orden de Pago");
        PagosMenu.add(GenerarOrdenPagoItem);

        jMenuBar1.add(PagosMenu);

        RegistrosMenu.setMnemonic('r');
        RegistrosMenu.setText("Registros");

        ListarRegistrosMenuItem.setText("Listar registros");
        ListarRegistrosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListarRegistrosMenuItemActionPerformed(evt);
            }
        });
        RegistrosMenu.add(ListarRegistrosMenuItem);

        jMenuBar1.add(RegistrosMenu);

        AyudaMenu.setMnemonic('a');
        AyudaMenu.setText("Ayuda");

        AcercaDeMenuItem.setText("Acerca de");
        AcercaDeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeMenuItemActionPerformed(evt);
            }
        });
        AyudaMenu.add(AcercaDeMenuItem);

        jMenuBar1.add(AyudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        EliminarUsuarioGUI eliminarUsuarioGUI = new EliminarUsuarioGUI(this, true);
        eliminarUsuarioGUI.setLocationRelativeTo(this);
        eliminarUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_EliminarUsuarioMenuItemActionPerformed

    private void CrearParqueaderoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearParqueaderoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearParqueaderoMenuItemActionPerformed

    private void EliminarParqueaderoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarParqueaderoMenuItemActionPerformed
        // TODO add your handling code here:
        EliminarParqueaderoGUI eliminarParqueaderoGUI = new EliminarParqueaderoGUI(this, true);
        eliminarParqueaderoGUI.setLocationRelativeTo(this);
        eliminarParqueaderoGUI.setVisible(true);
    }//GEN-LAST:event_EliminarParqueaderoMenuItemActionPerformed

    private void AcercaDeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcercaDeMenuItemActionPerformed

    private void EliminarParqueaderoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarParqueaderoBtnActionPerformed
        // TODO add your handling code here:
        int row = TablaParqueaderos.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un parqueadero.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        String idParqueadero = (String) TablaParqueaderos.getValueAt(row, 1);
        EliminarParqueaderoGUI eliminarParqueaderoGUI = new EliminarParqueaderoGUI(this, true);
        eliminarParqueaderoGUI.cargarDatos(idParqueadero);
        eliminarParqueaderoGUI.setLocationRelativeTo(this);
        eliminarParqueaderoGUI.setVisible(true);
    }//GEN-LAST:event_EliminarParqueaderoBtnActionPerformed

    private void CrearParqueaderoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearParqueaderoBtnActionPerformed
        // TODO add your handling code here:
        String campus = (String) CampusCB.getSelectedItem();
        if(campus == null || campus.trim().length() == 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un campus.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
            
        CrearParqueaderoGUI crearParqueaderoGUI = new CrearParqueaderoGUI(this, true);
        crearParqueaderoGUI.setLocationRelativeTo(this);
        crearParqueaderoGUI.CargarDatos(campus);
        crearParqueaderoGUI.setVisible(true);
    }//GEN-LAST:event_CrearParqueaderoBtnActionPerformed

    private void CrearUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        CrearUsuarioGUI crearUsuarioGUI = new CrearUsuarioGUI(this, rootPaneCheckingEnabled);
        crearUsuarioGUI.setLocationRelativeTo(this);
        crearUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_CrearUsuarioMenuItemActionPerformed

    private void ModificarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        EditarUsuarioGUI editarUsuarioGUI = new EditarUsuarioGUI(this, rootPaneCheckingEnabled);
        editarUsuarioGUI.setLocationRelativeTo(this);
        editarUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_ModificarUsuarioMenuItemActionPerformed

    private void CrearUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBtnActionPerformed
        CrearUsuarioGUI crearUsuarioGUI = new CrearUsuarioGUI(this, rootPaneCheckingEnabled);
        crearUsuarioGUI.setLocationRelativeTo(this);
        crearUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_CrearUsuarioBtnActionPerformed
    
    private void ModificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioBtnActionPerformed
        int row = TablaUsuarios.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un usuario.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        String cedula = (String) TablaUsuarios.getValueAt(row, 1);
        
        EditarUsuarioGUI editarUsuarioGUI = new EditarUsuarioGUI(this, rootPaneCheckingEnabled);
        editarUsuarioGUI.setLocationRelativeTo(this);
        
        try {
            editarUsuarioGUI.cargarDatos(cedula);
            editarUsuarioGUI.habilitarCampos();
            editarUsuarioGUI.setVisible(true);
        } catch (UsuarioNoExistenteException | CedulaNoValidaException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_ModificarUsuarioBtnActionPerformed

    private void TipoUsuarioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUsuarioCBActionPerformed
        listarUsuarios();
    }//GEN-LAST:event_TipoUsuarioCBActionPerformed

    private void ListarRegistrosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListarRegistrosMenuItemActionPerformed
        RegistrosGUI registrosGUI = new RegistrosGUI(this, true);
        registrosGUI.setLocationRelativeTo(this);
        registrosGUI.setVisible(true);
    }//GEN-LAST:event_ListarRegistrosMenuItemActionPerformed

    private void CampusCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampusCBActionPerformed
        try {
            listarParqueaderos();
        } catch (CampusNoExistenteException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_CampusCBActionPerformed

    private void EliminarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioBtnActionPerformed
        // TODO add your handling code here:
        int row = TablaUsuarios.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un usuario.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        String cedula = (String) TablaUsuarios.getValueAt(row, 1);
        EliminarUsuarioGUI eliminarUsuarioGUI = new EliminarUsuarioGUI(this, rootPaneCheckingEnabled);
        eliminarUsuarioGUI.cargarDatos(cedula);
        eliminarUsuarioGUI.setLocationRelativeTo(this);
        eliminarUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_EliminarUsuarioBtnActionPerformed

    private void SalirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirItemActionPerformed

    private void EliminarCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCampusMenuItemActionPerformed
        // TODO add your handling code here:
        String nombreCampus = (String) CampusCB.getSelectedItem();
        if(nombreCampus==null){
            JOptionPane.showMessageDialog(rootPane, "No se a selecionado ningun campus", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        CampusService campusService = new CampusService();
        try {
            campusService.delCampus((String) CampusCB.getSelectedItem());
        } catch (CampusNoExistenteException | IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
        cargarParqueaderosCB();
    }//GEN-LAST:event_EliminarCampusMenuItemActionPerformed

    private void ModicarCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModicarCampusMenuItemActionPerformed
        // TODO add your handling code here:
        String nombreCampus = (String) CampusCB.getSelectedItem();
        if(nombreCampus==null){
            JOptionPane.showMessageDialog(rootPane, "No se a selecionado ningun campus", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        EditarCampusGUI editarCampusGUI = new EditarCampusGUI(this, rootPaneCheckingEnabled);
        editarCampusGUI.setLocationRelativeTo(this);
        try {
            editarCampusGUI.CargarDatos((String) CampusCB.getSelectedItem());
            editarCampusGUI.setVisible(true);
        } catch (CampusNoExistenteException | IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_ModicarCampusMenuItemActionPerformed

    private void CrearCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCampusMenuItemActionPerformed
        // TODO add your handling code here:
        CrearCampusGUI crearCampusGUI = new CrearCampusGUI(this, rootPaneCheckingEnabled);
        crearCampusGUI.setLocationRelativeTo(this);
        crearCampusGUI.setVisible(true);
    }//GEN-LAST:event_CrearCampusMenuItemActionPerformed

    private void AdministarPuertasMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministarPuertasMenuItemActionPerformed
        // TODO add your handling code here:
        AdministrarPuertasGUI administrarPuertasGUI = new AdministrarPuertasGUI(this, true);
        administrarPuertasGUI.setLocationRelativeTo(this);
        administrarPuertasGUI.setVisible(true);
    }//GEN-LAST:event_AdministarPuertasMenuItemActionPerformed

    private void AdministarPorterosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdministarPorterosMenuItemActionPerformed
        // TODO add your handling code here:
        AdministarPorterosGUI administarPorterosGUI = new AdministarPorterosGUI(this, rootPaneCheckingEnabled);
        administarPorterosGUI.setLocationRelativeTo(this);
        administarPorterosGUI.setVisible(true);
    }//GEN-LAST:event_AdministarPorterosMenuItemActionPerformed

    private void ModificarParqueaderoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarParqueaderoBtnActionPerformed
        // TODO add your handling code here:
        int row = TablaParqueaderos.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un parqueadero.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        String idParqueadero = (String) TablaParqueaderos.getValueAt(row, 1);
        
        EditarParqueaderoGUI editarParqueaderoGUI = new EditarParqueaderoGUI(this, true);
        editarParqueaderoGUI.setLocationRelativeTo(this);
               
        try {
            editarParqueaderoGUI.cargarDatos(idParqueadero);
            editarParqueaderoGUI.habilitarCampos();
            editarParqueaderoGUI.setVisible(true);
        } catch (ParqueaderoNoExistenteException | CodigoNoValidoException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage(), "Error", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_ModificarParqueaderoBtnActionPerformed

    private void ModificarParqueaderoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarParqueaderoMenuItemActionPerformed
        // TODO add your handling code here:

        EditarParqueaderoGUI editarParqueaderoGUI = new EditarParqueaderoGUI(this, true);
        editarParqueaderoGUI.setLocationRelativeTo(this);
        
        editarParqueaderoGUI.setVisible(true);
    }//GEN-LAST:event_ModificarParqueaderoMenuItemActionPerformed

    private void VerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerBtnActionPerformed
        // TODO add your handling code here:
        int row = TablaUsuarios.getSelectedRow();
        if(row < 0){
            JOptionPane.showMessageDialog(rootPane, "No se ha seleccionado un usuario.", "Mensaje", JOptionPane.OK_OPTION);
            return;
        }
        String cedula = (String) TablaUsuarios.getValueAt(row, 1);
        UsuarioGUI usuarioGUI = new UsuarioGUI(this, true);
        
        usuarioGUI.cargarDatos(cedula);
        
        usuarioGUI.setLocationRelativeTo(this);
        usuarioGUI.setVisible(true);
    }//GEN-LAST:event_VerBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDeMenuItem;
    private javax.swing.JMenuItem AdministarPorterosMenuItem;
    private javax.swing.JMenuItem AdministarPuertasMenuItem;
    private javax.swing.JMenuItem AgregarPuertaAccesoItem;
    private javax.swing.JMenuItem AgregarUsuarioParqueaderoItem;
    private javax.swing.JMenu AyudaMenu;
    private javax.swing.JComboBox CampusCB;
    private javax.swing.JMenu CampusMenu;
    private javax.swing.JMenuItem CrearCampusMenuItem;
    private javax.swing.JButton CrearParqueaderoBtn;
    private javax.swing.JMenuItem CrearParqueaderoMenuItem;
    private javax.swing.JButton CrearUsuarioBtn;
    private javax.swing.JMenuItem CrearUsuarioMenuItem;
    private javax.swing.JMenuItem EliminarCampusMenuItem;
    private javax.swing.JButton EliminarParqueaderoBtn;
    private javax.swing.JMenuItem EliminarParqueaderoMenuItem;
    private javax.swing.JMenuItem EliminarPuertaAccesoItem;
    private javax.swing.JButton EliminarUsuarioBtn;
    private javax.swing.JMenuItem EliminarUsuarioMenuItem;
    private javax.swing.JMenuItem EliminarUsuarioParqueaderoItem;
    private javax.swing.JMenuItem GenerarOrdenPagoItem;
    private javax.swing.JMenuItem ListarRegistrosMenuItem;
    private javax.swing.JMenuItem ModicarCampusMenuItem;
    private javax.swing.JButton ModificarParqueaderoBtn;
    private javax.swing.JMenuItem ModificarParqueaderoMenuItem;
    private javax.swing.JButton ModificarUsuarioBtn;
    private javax.swing.JMenuItem ModificarUsuarioMenuItem;
    private javax.swing.JMenu PagosMenu;
    private javax.swing.JMenu ParqueaderosMenu;
    private javax.swing.JMenu RegistrosMenu;
    private javax.swing.JMenuItem SalirItem;
    private javax.swing.JTable TablaParqueaderos;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JComboBox TipoUsuarioCB;
    private javax.swing.JMenu UsuariosMenu;
    private javax.swing.JButton VerBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
