/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package edu.ucue.jparking.gui;

//import static javafx.application.Platform.exit;

import edu.ucue.jparking.dao.excepciones.UsuarioYaExistenteException;
import edu.ucue.jparking.srv.UsuarioService;
import edu.ucue.jparking.srv.enums.TipoUsuario;
import edu.ucue.jparking.srv.excepciones.CedulaNoValidaException;
import edu.ucue.jparking.srv.objetos.Usuario;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author Franklin Lara
 */
public class PrincipalGUI extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalGUI
     */
    public PrincipalGUI() {
        initComponents();
        ImageIcon imgIcon = new ImageIcon("../JParking/img/transport122.png");
        this.setIconImage(imgIcon.getImage());
        listarUsuarios();
        setLocationRelativeTo(null);
    }
    
        private void listarUsuarios(){        
        UsuarioService usuarioService = new UsuarioService();
        
        String tipoUsuario = (String) TipoUsuarioCB.getSelectedItem();
        Set<Usuario> usuarios = null;
        switch(tipoUsuario){
            case "Todos": {
                usuarios = usuarioService.getLista();
                break;
            }
            case "Estudiante":{
                usuarios = usuarioService.getLista(TipoUsuario.ESTUDIANTE);
                break;
            }
            case "Docente": {
                usuarios = usuarioService.getLista(TipoUsuario.DOCENTE);
                break;
            }
            case "Empleado": {
                usuarios = usuarioService.getLista(TipoUsuario.EMPLEADO);
                break;
            }
        }
        
        DefaultTableModel model = (DefaultTableModel) TablaUsuarios.getModel();
        
        //Borrar elementos anteriores
        for(int i = 0; i < model.getRowCount(); i++)
            model.removeRow(i);
        
        int n = 1;
        for(Usuario u : usuarios)
            model.addRow(new Object[]{n++, u.getCedula(), u.getNombres() + " " + u.getApellidos()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CampusCB = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaParqueaderos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        CrearParqueaderoBtn = new javax.swing.JButton();
        ModificarParqueaderoBtn = new javax.swing.JButton();
        EliminarParqueaderoBtn = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaUsuarios = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        TipoUsuarioCB = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        ModificarUsuarioBtn = new javax.swing.JButton();
        CrearUsuarioBtn = new javax.swing.JButton();
        EliminarUsuarioBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        CampusMenu = new javax.swing.JMenu();
        CrearCampusMenuItem = new javax.swing.JMenuItem();
        ModicarCampusMenuItem = new javax.swing.JMenuItem();
        EliminarCampusMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        CrearPuertaItem = new javax.swing.JMenuItem();
        EditarPuertaItem = new javax.swing.JMenuItem();
        EliminarPuertaItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        CrearPorteroItem = new javax.swing.JMenuItem();
        EditarPorteroItem = new javax.swing.JMenuItem();
        EliminarPorteroItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        SalirItem = new javax.swing.JMenuItem();
        UsuariosMenu = new javax.swing.JMenu();
        CrearUsuarioMenuItem = new javax.swing.JMenuItem();
        ModificarUsuarioMenuItem = new javax.swing.JMenuItem();
        EliminarUsuarioMenuItem = new javax.swing.JMenuItem();
        ParqueaderosMenu = new javax.swing.JMenu();
        CrearParqueaderoMenuItem = new javax.swing.JMenuItem();
        ModificarParqueaderoMenuItem = new javax.swing.JMenuItem();
        EliminarParqueaderoMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        AgregarPuertaAccesoItem = new javax.swing.JMenuItem();
        EliminarPuertaAccesoItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        AgregarUsuarioParqueaderoItem = new javax.swing.JMenuItem();
        EliminarUsuarioParqueaderoItem = new javax.swing.JMenuItem();
        PagosMenu = new javax.swing.JMenu();
        GenerarOrdenPagoItem = new javax.swing.JMenuItem();
        RegistrosMenu = new javax.swing.JMenu();
        ListarRegistrosMenuItem = new javax.swing.JMenuItem();
        AyudaMenu = new javax.swing.JMenu();
        AcercaDeMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JParking- Gestion de los Parqueaderos de la Universidad de Cuenca");

        jSplitPane1.setDividerLocation(350);
        jSplitPane1.setDividerSize(15);
        jSplitPane1.setAutoscrolls(true);
        jSplitPane1.setOneTouchExpandable(true);

        jLabel1.setText("Campus:");

        TablaParqueaderos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Id", "Ubicación", "Num Parqueaderos", "Espacios Disponibles"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaParqueaderos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaParqueaderos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TablaParqueaderos);
        if (TablaParqueaderos.getColumnModel().getColumnCount() > 0) {
            TablaParqueaderos.getColumnModel().getColumn(0).setMinWidth(30);
            TablaParqueaderos.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaParqueaderos.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        CrearParqueaderoBtn.setText("Crear");
        CrearParqueaderoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearParqueaderoBtnActionPerformed(evt);
            }
        });

        ModificarParqueaderoBtn.setText("Modificar");

        EliminarParqueaderoBtn.setText("Eliminar");
        EliminarParqueaderoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarParqueaderoBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(CrearParqueaderoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarParqueaderoBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarParqueaderoBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearParqueaderoBtn)
                    .addComponent(ModificarParqueaderoBtn)
                    .addComponent(EliminarParqueaderoBtn)))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampusCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE)))
                        .addGap(10, 10, 10)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CampusCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Parqueaderos", jPanel2);

        jSplitPane1.setRightComponent(jTabbedPane1);

        TablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Cedula", "Nombre"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaUsuarios.setMaximumSize(new java.awt.Dimension(2147483647, 16));
        TablaUsuarios.setMinimumSize(new java.awt.Dimension(60, 16));
        TablaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        TablaUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TablaUsuarios);
        if (TablaUsuarios.getColumnModel().getColumnCount() > 0) {
            TablaUsuarios.getColumnModel().getColumn(0).setMinWidth(30);
            TablaUsuarios.getColumnModel().getColumn(0).setPreferredWidth(30);
            TablaUsuarios.getColumnModel().getColumn(0).setMaxWidth(30);
        }

        jLabel4.setText("Tipo Usuario:");

        TipoUsuarioCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Docente", "Empleado", "Estudiante" }));
        TipoUsuarioCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TipoUsuarioCBActionPerformed(evt);
            }
        });

        ModificarUsuarioBtn.setText("Modificar");
        ModificarUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioBtnActionPerformed(evt);
            }
        });

        CrearUsuarioBtn.setText("Crear");
        CrearUsuarioBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBtnActionPerformed(evt);
            }
        });

        EliminarUsuarioBtn.setText("Eliminar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(CrearUsuarioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ModificarUsuarioBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EliminarUsuarioBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CrearUsuarioBtn)
                    .addComponent(ModificarUsuarioBtn)
                    .addComponent(EliminarUsuarioBtn))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(TipoUsuarioCB, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TipoUsuarioCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Usuarios", jPanel1);

        jSplitPane1.setLeftComponent(jTabbedPane2);

        CampusMenu.setMnemonic('c');
        CampusMenu.setText("Campus");

        CrearCampusMenuItem.setText("Crear Campus");
        CrearCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(CrearCampusMenuItem);

        ModicarCampusMenuItem.setText("Editar Campus");
        ModicarCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModicarCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(ModicarCampusMenuItem);

        EliminarCampusMenuItem.setText("Eliminar Campus");
        EliminarCampusMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCampusMenuItemActionPerformed(evt);
            }
        });
        CampusMenu.add(EliminarCampusMenuItem);
        CampusMenu.add(jSeparator1);

        CrearPuertaItem.setText("Crear puerta");
        CrearPuertaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPuertaItemActionPerformed(evt);
            }
        });
        CampusMenu.add(CrearPuertaItem);

        EditarPuertaItem.setText("Editar puerta");
        EditarPuertaItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPuertaItemActionPerformed(evt);
            }
        });
        CampusMenu.add(EditarPuertaItem);

        EliminarPuertaItem.setText("Eliminar puerta");
        CampusMenu.add(EliminarPuertaItem);
        CampusMenu.add(jSeparator3);

        CrearPorteroItem.setText("Crear portero");
        CrearPorteroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearPorteroItemActionPerformed(evt);
            }
        });
        CampusMenu.add(CrearPorteroItem);

        EditarPorteroItem.setText("Editar portero");
        EditarPorteroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditarPorteroItemActionPerformed(evt);
            }
        });
        CampusMenu.add(EditarPorteroItem);

        EliminarPorteroItem.setText("Eliminar portero");
        EliminarPorteroItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarPorteroItemActionPerformed(evt);
            }
        });
        CampusMenu.add(EliminarPorteroItem);
        CampusMenu.add(jSeparator2);

        SalirItem.setText("Salir");
        SalirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirItemActionPerformed(evt);
            }
        });
        CampusMenu.add(SalirItem);

        jMenuBar1.add(CampusMenu);

        UsuariosMenu.setMnemonic('u');
        UsuariosMenu.setText("Usuarios");

        CrearUsuarioMenuItem.setText("Crear Usuario");
        CrearUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(CrearUsuarioMenuItem);

        ModificarUsuarioMenuItem.setText("Modificar Usuario");
        ModificarUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(ModificarUsuarioMenuItem);

        EliminarUsuarioMenuItem.setText("Eliminar  Usuario");
        EliminarUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarUsuarioMenuItemActionPerformed(evt);
            }
        });
        UsuariosMenu.add(EliminarUsuarioMenuItem);

        jMenuBar1.add(UsuariosMenu);

        ParqueaderosMenu.setMnemonic('p');
        ParqueaderosMenu.setText("Parqueaderos");

        CrearParqueaderoMenuItem.setText("Crear Parqueadero");
        CrearParqueaderoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearParqueaderoMenuItemActionPerformed(evt);
            }
        });
        ParqueaderosMenu.add(CrearParqueaderoMenuItem);

        ModificarParqueaderoMenuItem.setText("Modificar Parqueadero");
        ParqueaderosMenu.add(ModificarParqueaderoMenuItem);

        EliminarParqueaderoMenuItem.setText("Eliminar Parqueadero");
        EliminarParqueaderoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarParqueaderoMenuItemActionPerformed(evt);
            }
        });
        ParqueaderosMenu.add(EliminarParqueaderoMenuItem);
        ParqueaderosMenu.add(jSeparator4);

        AgregarPuertaAccesoItem.setText("Agregar puerta de acceso");
        ParqueaderosMenu.add(AgregarPuertaAccesoItem);

        EliminarPuertaAccesoItem.setText("Eliminar puerta de acceso");
        ParqueaderosMenu.add(EliminarPuertaAccesoItem);
        ParqueaderosMenu.add(jSeparator5);

        AgregarUsuarioParqueaderoItem.setText("Agregar usuario");
        ParqueaderosMenu.add(AgregarUsuarioParqueaderoItem);

        EliminarUsuarioParqueaderoItem.setText("Eliminar usuario");
        ParqueaderosMenu.add(EliminarUsuarioParqueaderoItem);

        jMenuBar1.add(ParqueaderosMenu);

        PagosMenu.setMnemonic('g');
        PagosMenu.setText("Pagos");

        GenerarOrdenPagoItem.setText("Generar Orden de Pago");
        PagosMenu.add(GenerarOrdenPagoItem);

        jMenuBar1.add(PagosMenu);

        RegistrosMenu.setMnemonic('r');
        RegistrosMenu.setText("Registros");

        ListarRegistrosMenuItem.setText("Listar registros");
        RegistrosMenu.add(ListarRegistrosMenuItem);

        jMenuBar1.add(RegistrosMenu);

        AyudaMenu.setMnemonic('a');
        AyudaMenu.setText("Ayuda");

        AcercaDeMenuItem.setText("Acerca de");
        AcercaDeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AcercaDeMenuItemActionPerformed(evt);
            }
        });
        AyudaMenu.add(AcercaDeMenuItem);

        jMenuBar1.add(AyudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarUsuarioMenuItemActionPerformed

    private void CrearParqueaderoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearParqueaderoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearParqueaderoMenuItemActionPerformed

    private void EliminarParqueaderoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarParqueaderoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarParqueaderoMenuItemActionPerformed

    private void AcercaDeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AcercaDeMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AcercaDeMenuItemActionPerformed

    private void SalirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirItemActionPerformed

    private void EliminarParqueaderoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarParqueaderoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarParqueaderoBtnActionPerformed

    private void CrearParqueaderoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearParqueaderoBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CrearParqueaderoBtnActionPerformed

    private void CrearCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearCampusMenuItemActionPerformed
        // TODO add your handling code here:
        CrearCampusGUI crearCampusGUI = new CrearCampusGUI();
        crearCampusGUI.setLocationRelativeTo(this);
        crearCampusGUI.setVisible(true);
    }//GEN-LAST:event_CrearCampusMenuItemActionPerformed

    private void CrearPuertaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPuertaItemActionPerformed
        // TODO add your handling code here:
        CrearPuertaGUI crearPuertaGUI = new CrearPuertaGUI();
        crearPuertaGUI.setVisible(true);
    }//GEN-LAST:event_CrearPuertaItemActionPerformed

    private void CrearUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        CrearUsuarioGUI crearUsuarioGUI = new CrearUsuarioGUI();
        crearUsuarioGUI.setLocationRelativeTo(this);
        crearUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_CrearUsuarioMenuItemActionPerformed

    private void ModicarCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModicarCampusMenuItemActionPerformed
        // TODO add your handling code here:
        EditarCampusGUI editarCampusGUI = new EditarCampusGUI();
        editarCampusGUI.setVisible(true);
    }//GEN-LAST:event_ModicarCampusMenuItemActionPerformed

    private void EditarPuertaItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPuertaItemActionPerformed
        // TODO add your handling code here:
        EditarPuertaGUI editarPuertaGUI = new EditarPuertaGUI();
        editarPuertaGUI.setVisible(true);
    }//GEN-LAST:event_EditarPuertaItemActionPerformed

    private void CrearPorteroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearPorteroItemActionPerformed
        // TODO add your handling code here:
        CrearPuertaGUI crearPuertaGUI = new CrearPuertaGUI();
        crearPuertaGUI.setVisible(true);
    }//GEN-LAST:event_CrearPorteroItemActionPerformed

    private void EliminarCampusMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCampusMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarCampusMenuItemActionPerformed

    private void EditarPorteroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarPorteroItemActionPerformed
        // TODO add your handling code here:
        EditarPorteroGUI editarPorteroGUI = new EditarPorteroGUI();
        editarPorteroGUI.setVisible(true);
    }//GEN-LAST:event_EditarPorteroItemActionPerformed

    private void EliminarPorteroItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarPorteroItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EliminarPorteroItemActionPerformed

    private void ModificarUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        EditarUsuarioGUI editarUsuarioGUI = new EditarUsuarioGUI();
        editarUsuarioGUI.setLocationRelativeTo(this);
        editarUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_ModificarUsuarioMenuItemActionPerformed

    private void CrearUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBtnActionPerformed
        CrearUsuarioGUI crearUsuarioGUI = new CrearUsuarioGUI();
        crearUsuarioGUI.setLocationRelativeTo(this);
        crearUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_CrearUsuarioBtnActionPerformed
    
    private void ModificarUsuarioBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarUsuarioBtnActionPerformed
        EditarUsuarioGUI editarUsuarioGUI = new EditarUsuarioGUI();
        editarUsuarioGUI.setLocationRelativeTo(this);
        editarUsuarioGUI.setVisible(true);
    }//GEN-LAST:event_ModificarUsuarioBtnActionPerformed

    private void TipoUsuarioCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TipoUsuarioCBActionPerformed
        listarUsuarios();
    }//GEN-LAST:event_TipoUsuarioCBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrincipalGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrincipalGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AcercaDeMenuItem;
    private javax.swing.JMenuItem AgregarPuertaAccesoItem;
    private javax.swing.JMenuItem AgregarUsuarioParqueaderoItem;
    private javax.swing.JMenu AyudaMenu;
    private javax.swing.JComboBox CampusCB;
    private javax.swing.JMenu CampusMenu;
    private javax.swing.JMenuItem CrearCampusMenuItem;
    private javax.swing.JButton CrearParqueaderoBtn;
    private javax.swing.JMenuItem CrearParqueaderoMenuItem;
    private javax.swing.JMenuItem CrearPorteroItem;
    private javax.swing.JMenuItem CrearPuertaItem;
    private javax.swing.JButton CrearUsuarioBtn;
    private javax.swing.JMenuItem CrearUsuarioMenuItem;
    private javax.swing.JMenuItem EditarPorteroItem;
    private javax.swing.JMenuItem EditarPuertaItem;
    private javax.swing.JMenuItem EliminarCampusMenuItem;
    private javax.swing.JButton EliminarParqueaderoBtn;
    private javax.swing.JMenuItem EliminarParqueaderoMenuItem;
    private javax.swing.JMenuItem EliminarPorteroItem;
    private javax.swing.JMenuItem EliminarPuertaAccesoItem;
    private javax.swing.JMenuItem EliminarPuertaItem;
    private javax.swing.JButton EliminarUsuarioBtn;
    private javax.swing.JMenuItem EliminarUsuarioMenuItem;
    private javax.swing.JMenuItem EliminarUsuarioParqueaderoItem;
    private javax.swing.JMenuItem GenerarOrdenPagoItem;
    private javax.swing.JMenuItem ListarRegistrosMenuItem;
    private javax.swing.JMenuItem ModicarCampusMenuItem;
    private javax.swing.JButton ModificarParqueaderoBtn;
    private javax.swing.JMenuItem ModificarParqueaderoMenuItem;
    private javax.swing.JButton ModificarUsuarioBtn;
    private javax.swing.JMenuItem ModificarUsuarioMenuItem;
    private javax.swing.JMenu PagosMenu;
    private javax.swing.JMenu ParqueaderosMenu;
    private javax.swing.JMenu RegistrosMenu;
    private javax.swing.JMenuItem SalirItem;
    private javax.swing.JTable TablaParqueaderos;
    private javax.swing.JTable TablaUsuarios;
    private javax.swing.JComboBox TipoUsuarioCB;
    private javax.swing.JMenu UsuariosMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
